Added email-domain flag to restrict access to given domain
negz/kuberos pull request #32
Opened 2018-04-24 01:16 UTC by keattang

Specifying the --email-domain flag allows you to prevent users with emails that don't match the given domain from accessing your secrets. This allows you to more confidently and securely expose kuberos to the internet

This is my first time writing go so please excuse any obvious mistakes. Happy to accept/implement feedback

2018-04-25 18:27 UTC, negz commented
@keattang It's been a while, but I feel like I've managed to get this behaviour without code changes before - I think via a setting at Google's end of a Google OIDC setup. I imagine not all OIDC providers let you filter via domain, so this seems reasonable.

2018-04-25 18:31 UTC, negz requested changes

2018-04-25 18:31 UTC, negz commented on README.md
> +                         this domain
A nitpick, but I'd prefer this help output be created by running `kuberos --help` and pasting it in. It's already a bit stale so you'd be doing me a favour. :)

2018-04-25 18:31 UTC, negz commented on extractor/oidc.go
> +func NewOIDC(v *oidc.IDTokenVerifier, emailDomain string, oo ...Option) (OIDC, error) {
I've tried to stick to a pattern in which only mandatory arguments (for example the `*oidc.IDTokenVerifier`) are 'first class' arguments to `NewOIDC`, with optional arguments implemented as `Option`s. Would you be willing to take a shot at copying the `Option` pattern for the email domain option?

2018-04-25 21:23 UTC, keattang commented on README.md
> +                         this domain
Done :)

2018-04-25 21:23 UTC, keattang commented on extractor/oidc.go
> +func NewOIDC(v *oidc.IDTokenVerifier, emailDomain string, oo ...Option) (OIDC, error) {
It appears below that you are looping over the options and calling them as functions on the `oe` object. I wasn't quite sure how to unpick that. What would you suggest?

2018-04-28 06:38 UTC, negz commented on cmd/kuberos/kuberos.go
> +		emailDomain = app.Flag("email-domain", "The eamil domain to restrict access to.").String()
Just noticed there's a typo in `email` here.

2018-04-28 06:41 UTC, negz commented on extractor/oidc.go
> +	emailDomain string
This looks like it needs `gofmt` run on it to align `string` with the above types.

2018-04-28 06:46 UTC, negz commented on extractor/oidc.go
> +func NewOIDC(v *oidc.IDTokenVerifier, emailDomain string, oo ...Option) (OIDC, error) {
Yeah, that's the pattern I was suggesting. In this specific case you've already added `emailDomain` so the idea is to add an 'option' function that takes an `oidcExtractor` as an argument and sets `emailDomain`. There's a good article about the pattern [here](https://dave.cheney.net/2014/10/17/functional-options-for-friendly-apis).

Something like:
```go
func EmailDomain(domain *string) Option {
	return func(o *oidcExtractor) error {
		o.emailDomain = domain
		return nil
	}
}
```

That way the following call will result in the default (i.e. an extractor `emailDomain` set to the empty string):
```go
e, err := extractor.NewOIDC(provider.Verifier(&oidc.Config{ClientID: *clientID}))
```

While this call will result in a custom email domain:
```go
e, err := extractor.NewOIDC(provider.Verifier(&oidc.Config{ClientID: *clientID}), extractor.EmailDomain("example.org"))
```

2018-04-29 06:33 UTC, keattang commented
@negz I implemented the changes you suggested. I also rebased my branch on your master but github seems to be showing those changes as part of the PR for some reason. I can close this and open another PR so that you just see my changes if you'd like?

2018-06-01 01:02 UTC, negz commented
@keattang Apologies for the super slow reply!

I've often fixed issues similar to this by running (from your branch):
```
# You might want to replace origin with upstream to rebase on github.com/negz rather than your fork's master
git fetch origin
git rebase origin/master
git push --force
```

2018-06-04 07:06 UTC, keattang commented
@negz that seems to have done the trick

2018-06-05 05:06 UTC, negz approved these changes

2018-06-05 05:07 UTC, merged

2018-06-05 05:07 UTC, negz commented
Merged! Thanks again, and sorry it took so long to merge this.

2018-06-05 05:21 UTC, keattang commented
Awesome thanks! Any idea on when that may be released to docker hub? Would love to get back on to the official release

2018-06-05 05:25 UTC, negz commented
@keattang It's there already; Travis pushes master to Docker Hub whenever a PR is merged. `negz/kuberos:ab5b206` should include your changes.

2018-06-05 05:29 UTC, keattang commented
great!